---
name: mcvs-general-action
description: |
  The Mission Critical Vulnerability Scanner (MCVS) General action.
inputs:
  testing-type:
    description: |
      The testing type, e.g. integration, unit or some other.
  yamllint-version:
    default: 1.37.1
    description: The version of YAMLLint.
  yamllint-sha256-hash:
    default: 364f0d79e81409f591e323725e6a9f4504c8699ddf2d7263d8d2b539cd66a583
    description: The sha256 hash of a certain yamllint package.
  yamllint-dependency-pathspec-version:
    default: 1.0.4
    description: The version of pathspec.
  yamllint-dependency-pathspec-sha256-hash:
    default: fb6ae2fd4e7c921a165808a552060e722767cfa526f99ca5156ed2ce45a5c723
    description: The sha256 hash of a certain pathspec package.
  yamllint-dependency-pyyaml-version:
    default: 6.0.3
    description: The version of PyYAML.
  yamllint-dependency-pyyaml-sha256-hash:
    default: ba1cc08a7ccde2d2ec775841541641e4548226580ab850948cbfda66a1befcdc
    description: The sha256 hash of a certain PyYAML package.
runs:
  using: composite
  steps:
    - if: |
        github.event_name == 'pull_request' &&
        (inputs.testing-type == 'lint-commit' ||
          inputs.testing-type == 'lint-git')
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - if: |
        github.event_name == 'pull_request' &&
        inputs.testing-type == 'lint-commit'
      run: |
        npm install --save-dev \
          commitlint-plugin-function-rules \
          @commitlint/{cli,config-conventional,ensure}

        cat ${GITHUB_ACTION_PATH}/configs/commitlint.config.mjs > \
          commitlint.config.mjs

        npx commitlint \
          --from ${{ github.event.pull_request.base.sha }} \
          --to ${{ github.event.pull_request.head.sha }} \
          --verbose
      shell: bash
    - if: |
        github.event_name == 'pull_request' &&
        inputs.testing-type == 'lint-git'
      run: |
        git fetch origin main
        git checkout main
        git checkout ${{ github.event.pull_request.head.ref }}
      shell: bash
    - if: |
        github.event_name == 'pull_request' &&
        inputs.testing-type == 'lint-git'
      run: |
        commits_behind=$(git rev-list --count HEAD..origin/main)
        if (( commits_behind > 0 )); then
          echo "❗ Branch is behind main by $commits_behind commits"
          exit 1
        fi
        echo "✅ Branch is up to date with main"
      shell: bash
    # yamllint disable rule:line-length
    - if: |
        github.event_name == 'pull_request' &&
        inputs.testing-type == 'lint-git'
      run: |
        MAIN_BRANCH="main"
        REMOTE="origin"

        current_branch=$(git rev-parse --abbrev-ref HEAD)

        if [[ "${current_branch}" == "${MAIN_BRANCH}" ]]; then
          echo "Already on ${MAIN_BRANCH}, nothing to check."
          exit 0
        fi

        commits=$(git rev-list $MAIN_BRANCH..HEAD --merges)

        for sha in $commits; do
          p1=$(git rev-parse "$sha^1")
          p2=$(git rev-parse "$sha^2")

          if git merge-base --is-ancestor "${p1}" "${REMOTE}/${MAIN_BRANCH}" && ! git merge-base --is-ancestor "${p2}" "${REMOTE}/${MAIN_BRANCH}"; then
            merged_from="${p1}"
          elif git merge-base --is-ancestor "${p2}" "${REMOTE}/${MAIN_BRANCH}" && ! git merge-base --is-ancestor "${p1}" "${REMOTE}/${MAIN_BRANCH}"; then
            merged_from="${p2}"
          else
            continue
          fi

          echo "❗ Detected a merge of ${MAIN_BRANCH} into ${current_branch} at commit ${sha}"
          echo "  Commit message: $(git log --format=%s -n 1 $sha)"
          exit 1
        done

        echo "✅ No merges of ${MAIN_BRANCH} detected in ${current_branch}"
        exit 0
      shell: bash
    - if: |
        github.event_name == 'pull_request' &&
        inputs.testing-type == 'lint-git'
      run: |
        fixup_commits=$(git log --oneline --grep="^fixup!" --grep="^squash!" origin/main..HEAD)
        if [ -n "$fixup_commits" ]; then
          echo "❗ Found fixup or squash commits that should be squashed:"
          echo "$fixup_commits"
          exit 1
        fi
        echo "✅ No fixup or squash commits found"
      shell: bash
    - if: inputs.testing-type == 'yamllint'
      run: |
        cat > /tmp/req.txt <<EOF
        yamllint==${{ inputs.yamllint-version }} --hash=sha256:${{ inputs.yamllint-sha256-hash }}
        pathspec==${{ inputs.yamllint-dependency-pathspec-version }} --hash=sha256:${{ inputs.yamllint-dependency-pathspec-sha256-hash }}
        pyyaml==${{ inputs.yamllint-dependency-pyyaml-version }} --hash=sha256:${{ inputs.yamllint-dependency-pyyaml-sha256-hash }}
        EOF
        cat /tmp/req.txt
        python3 -m pip install --require-hashes --user -r /tmp/req.txt
        yamllint -c ${GITHUB_ACTION_PATH}/configs/yamllint.yaml .
      shell: bash
